### PR TITLE
mvvm refactor

### PR DESCRIPTION
**Pull request by dvirberlo**
what do you think?

### CODE REVIEW

**Comment by dvirberlo** [comment]
#19

**Comment by dvirberlo** [comment]
and #20

**Comment by eternaleclipse** [comment]
Looks really, really good!!
There are some conflicts, I assume because some changes were introduced since the PR.
Would love to have a discord session, review, discuss everything and merge if you are available - please let me know.
Not sure about the split between Preferences / Game VM. In theory it should be fine until they need each other, but it could make the dependencies a bit over-complicated when testing.

**Comment by dvirberlo** [comment]
No problem.
Conflics solved.
Now trying the `mobx` path.

**Pull request closed without merging**
