### PR TITLE
Feat/explanation popups (title)

### PR DESCRIPTION
**Pull request by lidor12456**
I used "title" property  in "ActionButton.tsx" to add some description for the buttons on main screen.

### CODE REVIEW

**Comment by dvirberlo** [comment]
Please change the destination branch of the PR to `develop`.

**Comment by dvirberlo** [comment]
Other than that, looks good to me @eternaleclipse

**Comment by shootermv** [comment]
lot of commits... may be good idea - can be to squash them
`git rebase -I HEAD~num-of-commits` command may be usefull

**Comment by dvirberlo** [comment]
Apperantely I can change it. And I just did.
Waiting for @eternaleclipse for final approval.
Well done

**Comment by eternaleclipse** [comment]
Great work! Cheers 🍻

**Pull request merged**
