### PR TITLE
feat: add solved puzzles list

### PR DESCRIPTION
**Pull request by dvirberlo**
#16

### CODE REVIEW

**Comment by eternaleclipse** [comment]
Found another problem - the puzzles should appear in sorted order and not in the order they were solved.

**Comment by dvirberlo** [comment]
> Thanks! The component looks great. But, I think it should always appear at the bottom, and when there are no solved puzzles it can show "Solved: (None)".

Do you mean the text "(None)".
Or just nothing?
The second seem unnatural, the first can be more friendly like "nothing is here yet" or something

**Comment by dvirberlo** [comment]
> Found another problem - the puzzles should appear in sorted order and not in the order they were solved.

Yes.
I think I should use `Set` instead of array.
It will be also more efficient, when scaled

**Comment by eternaleclipse** [comment]
> 

The text "None" inside the ellipse - This is also the behavior in the old design. For something friendlier, maybe "None, yet 😉".

Cheers 🍻

**Comment by dvirberlo** [comment]
done @eternaleclipse

**Pull request merged**
