### PR TITLE
fix: board overflow

### LINKED ISSUE #15: Fix board overflow in brave mobile

### PR DESCRIPTION
**Pull request by yaelih**
fix #15

### CODE REVIEW

**Comment by yaelih** [comment]
@eternaleclipse can you check it on your mobile please?

**Comment by dvirberlo** [comment]
Your first commit changed also Board.tsx
Was it on purpose?
If not, you can add new commit to revert the changes? (See "Files Changed"  section)

**Comment by yaelih** [comment]
It was intended. Only removing overflow-hidden caused other issues in other screen sizes due to css in board.

**Comment by dvirberlo** [comment]
I fear, then, that you introduced other old bugs:
Screenshot_20230425_081750_Chrome

**Comment by eternaleclipse** [comment]
Testing on iPhone 12 SE running on Brave Version 1.49.1 (latest, on iOS):

https://user-images.githubusercontent.com/12075301/234227888-c337adda-75b7-4d16-8865-7af3a244e25e.mp4

There are several behaviors that can be observed here.
1. When the app starts, on Puzzle 1, the board is squeezed.
2. When moving to the next puzzle, the board resets to a good layout that covers the entire width - this is great! This is the same for puzzles 2-6.
3. However, in these puzzles, the user cannot scroll down (this may be because of the other container having `overflow-hidden`. This is the same for puzzles 2-6.
4. When the user goes back to to puzzle 1, the board shifts right and overflows out of the screen.

I'm working on getting us a free subscription to BrowserStack for easier testing.
They have a life-time sponsorship program for open-source projects.
https://www.browserstack.com/open-source

**Comment by eternaleclipse** [comment]
fixed in #92

**Pull request closed without merging**
